# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import echo_pb2 as echo__pb2


class EchoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RotaryFieldEcho = channel.unary_unary(
                '/dz4.EchoService/RotaryFieldEcho',
                request_serializer=echo__pb2.RotaryFieldRequest.SerializeToString,
                response_deserializer=echo__pb2.RotaryFieldResponce.FromString,
                )
        self.PointEcho = channel.unary_unary(
                '/dz4.EchoService/PointEcho',
                request_serializer=echo__pb2.Vect2.SerializeToString,
                response_deserializer=echo__pb2.Vect2.FromString,
                )
        self.SequenceEcho = channel.unary_unary(
                '/dz4.EchoService/SequenceEcho',
                request_serializer=echo__pb2.Sequence.SerializeToString,
                response_deserializer=echo__pb2.Sequence.FromString,
                )


class EchoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RotaryFieldEcho(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PointEcho(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SequenceEcho(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RotaryFieldEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.RotaryFieldEcho,
                    request_deserializer=echo__pb2.RotaryFieldRequest.FromString,
                    response_serializer=echo__pb2.RotaryFieldResponce.SerializeToString,
            ),
            'PointEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.PointEcho,
                    request_deserializer=echo__pb2.Vect2.FromString,
                    response_serializer=echo__pb2.Vect2.SerializeToString,
            ),
            'SequenceEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.SequenceEcho,
                    request_deserializer=echo__pb2.Sequence.FromString,
                    response_serializer=echo__pb2.Sequence.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dz4.EchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EchoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RotaryFieldEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dz4.EchoService/RotaryFieldEcho',
            echo__pb2.RotaryFieldRequest.SerializeToString,
            echo__pb2.RotaryFieldResponce.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PointEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dz4.EchoService/PointEcho',
            echo__pb2.Vect2.SerializeToString,
            echo__pb2.Vect2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SequenceEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dz4.EchoService/SequenceEcho',
            echo__pb2.Sequence.SerializeToString,
            echo__pb2.Sequence.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
