# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x03\x64z4\"%\n\x05Vect2\x12\r\n\x05val_x\x18\x01 \x01(\x02\x12\r\n\x05val_y\x18\x02 \x01(\x02\"^\n\x13RotaryFieldResponce\x12\x19\n\x05point\x18\x01 \x01(\x0b\x32\n.dz4.Vect2\x12\x19\n\x05\x66ield\x18\x02 \x01(\x0b\x32\n.dz4.Vect2\x12\x11\n\tdirection\x18\x03 \x01(\t\"\xb2\x01\n\x12RotaryFieldRequest\x12\x19\n\x05point\x18\x01 \x01(\x0b\x32\n.dz4.Vect2\x12\x11\n\tdirection\x18\x02 \x01(\t\x12\x33\n\x06vector\x18\x03 \x03(\x0b\x32#.dz4.RotaryFieldRequest.VectorEntry\x1a\x39\n\x0bVectorEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.dz4.Vect2:\x02\x38\x01\"\x1b\n\x08Sequence\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\x32\xa6\x01\n\x0b\x45\x63hoService\x12\x44\n\x0fRotaryFieldEcho\x12\x17.dz4.RotaryFieldRequest\x1a\x18.dz4.RotaryFieldResponce\x12#\n\tPointEcho\x12\n.dz4.Vect2\x1a\n.dz4.Vect2\x12,\n\x0cSequenceEcho\x12\r.dz4.Sequence\x1a\r.dz4.Sequenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _ROTARYFIELDREQUEST_VECTORENTRY._options = None
  _ROTARYFIELDREQUEST_VECTORENTRY._serialized_options = b'8\001'
  _globals['_VECT2']._serialized_start=19
  _globals['_VECT2']._serialized_end=56
  _globals['_ROTARYFIELDRESPONCE']._serialized_start=58
  _globals['_ROTARYFIELDRESPONCE']._serialized_end=152
  _globals['_ROTARYFIELDREQUEST']._serialized_start=155
  _globals['_ROTARYFIELDREQUEST']._serialized_end=333
  _globals['_ROTARYFIELDREQUEST_VECTORENTRY']._serialized_start=276
  _globals['_ROTARYFIELDREQUEST_VECTORENTRY']._serialized_end=333
  _globals['_SEQUENCE']._serialized_start=335
  _globals['_SEQUENCE']._serialized_end=362
  _globals['_ECHOSERVICE']._serialized_start=365
  _globals['_ECHOSERVICE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
